# Generated by Django 2.1.7 on 2019-03-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='check_flag',
            field=models.BooleanField(default=False),
        ),
    ]
